# Generated by Django 5.0.1 on 2024-01-28 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('target_is_complated', models.BooleanField(default=False)),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_main_topic', to='apps.maintopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_main', to='time_tracking.timemaintopic')),
                ('sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_sub', to='apps.subtopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('hour', models.FloatField()),
                ('date', models.DateField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='time_tracking.timesubtopic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
