# Generated by Django 5.0.1 on 2024-01-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmaintopic',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionsubtopic',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
