# Generated by Django 5.0.1 on 2024-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_tracking', '0002_alter_questionmaintopic_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
